#!/bin/bash
# command line url-shorten

if [ -z $1 ];then
   echo "Insert a URL to be shortened":
   read URL
   LONG=$URL
else
   LONG=$1
fi

UR1='http://ur1.ca/'

/usr/bin/env curl -s $UR1 -d"longurl=$LONG"| sed -e '/Your ur1/!d;s: *::g;s:<[^>]*>::g;s:^.*Yourur1is\:h:h:;'
